name: flut_base_web_workspace
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  localization: 2.1.0
  flut_micro_app_auth:
    path: ../flut_micro_app_auth
    # git:
    #   url: "https://github.com/cuiatech/flut_micro_app_auth.git"
    #   ref: "master"
  flut_micro_app_dashboard:
    path: ../flut_micro_app_dashboard
    # git:
    #   url: "https://github.com/cuiatech/flut_micro_app_dashboard.git"
    #   ref: "master"
  flut_micro_app_help_center:
    path: ../flut_micro_app_help_center
    # git:
    #   url: "https://github.com/cuiatech/flut_micro_app_help_center.git"
    #   ref: "master"
  flut_micro_app_marketplace:
    path: ../flut_micro_app_marketplace
    # git:
    #   url: "https://github.com/cuiatech/flut_micro_app_marketplace.git"
    #   ref: "master"
  

dependency_overrides:
  flut_micro_commons_dependencies:
    path: ../flut_micro_commons_dependencies
    # git:
    #   url: "https://github.com/cuiatech/flut_micro_commons_dependencies.git"
    #   ref: "master"
  flut_micro_commons_client_https:
    path: ../flut_micro_commons_client_https
    # git:
    #   url: "https://github.com/cuiatech/flut_micro_commons_client_https.git"
    #   ref: "master"
  flut_micro_commons_shared:
    path: ../flut_micro_commons_shared
    # git:
    #   url: "https://github.com/cuiatech/flut_micro_commons_shared.git"
    #   ref: "master"
  flut_micro_commons_ds:
    path: ../flut_micro_commons_ds
    # git:
    #   url: "https://github.com/cuiatech/flut_micro_commons_ds.git"
    #   ref: "master"
  flut_micro_commons_auth:
    path: ../flut_micro_commons_auth
    # git:
    #   url: "https://github.com/cuiatech/flut_micro_commons_auth.git"
    #   ref: "master"
  flut_micro_commons_core_app:
    path: ../flut_micro_commons_core_app
    # git:
    #   url: "https://github.com/cuiatech/flut_micro_commons_core_app.git"
    #   ref: "master"
  flut_external_shopping_monitor:
    path: ../flut_external_shopping_monitor
    # git:
    #   url: "https://github.com/cuiatech/flut_external_shopping_monitor.git"
    #   ref: "master"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.0
  mobx_codegen: 2.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/lang/
